### ISSUE TITLE
PrintWriter log problem

### ISSUE THREAD

**Issue by sinanyumak** [librucha/servlet-logging-filter#10]
@librucha hello,

When a repsonse is prepared with PrintWriter, nothing is logged. 

I've created a simple PrintWriter which is flushing immediately after write operations. 

I would be happy to hear your opinion.

https://github.com/sinanyumak/servlet-logging-filter/commit/d752b1ae8db419d46b181985c99079f306859221

**Comment by librucha** [comment]
Hi @sinanyumak 
This project was used only for special operations with direct access to req/res and is not fully usable for every case.

I suggest use Spring wrappers for servler [req](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/ContentCachingRequestWrapper.html) / [res](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/util/ContentCachingResponseWrapper.html) or my coleague library https://github.com/etherealscope/request-logging which is working well
